[package]
name = "telemetry-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = { version = "1", features = ["derive"] }
serde-wasm-bindgen = "0.6"
telemetry-core = { path = "../telemetry-core" }
wasm-bindgen = "0.2"
